name: Python package
on:
    release:
        types: [published]
jobs:
    # https://github.com/marketplace/actions/pypi-publish
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/uoy-assessment-uploader
        permissions:
            id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            # retrieve your distributions here
            - uses: actions/checkout@v3
            # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.11'
                  cache: 'pipenv'
            - name: Install dependencies
              run: |
                  pip install --upgrade pip wheel setuptools pipenv
                  pipenv install --dev
            - name: Build
              run: pipenv run python -m build
            - uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist/
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  print-hash: true
                  skip-existing: true
                  verbose: true
