name: Python package
on:
    # todo remove push, use only release hook
#    push:
#        branches:
#            - main
    release:
        types: [published]
jobs:
    # https://github.com/marketplace/actions/pypi-publish
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: release
            url: https://pypi.org/p/uoy-assessment-uploader
        permissions:
            id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            # retrieve your distributions here
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.11'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel setuptools
                  python -m pip install --upgrade build
            - name: Build
              run: python -m build
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  print-hash: true
                  skip-existing: true
                  verbose: true
                  # todo switch to Trusted Publisher mode once that's available
                  password: ${{ secrets.PYPI_API_TOKEN }}
